### PR TITLE
Add port forwarding creation ability.

### PR DESCRIPTION
**Pull request by weia5-emc**
Add code to create port forwarding rules automatically.

### CODE REVIEW

**Comment by fub2** [comment]
This is sweet!

**Comment by fub2** [comment]
@xiar @XiaowenJiang

**Comment by XiaowenJiang** [comment]
This is awesome

**Comment by weia5-emc** [comment]
@fub2 conflict has been fixed.

**Comment by weia5-emc** [comment]
@fub2 @XiaowenJiang @xiar @chenge3 @bcyan

**Comment by weia5-emc** [comment]
beg your merge... 🐵

**Review by xiar — APPROVED** [review]
👍

**Comment by XiaowenJiang** [comment]
good

**Comment by chenge3** [comment]
👍

**Pull request merged**
